CREATE TABLE PARTICIPANTE(
    CODIGO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NOME VARCHAR (100) NOT NULL,
    EMAIL VARCHAR (100) NOT NULL,
    SENHA VARCHAR (100) NOT NULL,
    CONSTRAINT PK_CODIGO_PARTICIPANTE PRIMARY KEY (CODIGO)
);

CREATE TABLE EVENTO(
    CODIGO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    TITULO VARCHAR (100) NOT NULL,
    MINIMO DECIMAL (5,2) NOT NULL,
    DATAEVENTO VARCHAR(10) NOT NULL,
    DATASORTEIO VARCHAR(10) NOT NULL,
    CODCRIADOR INTEGER NOT NULL,
	SORTEADO BOOLEAN,
    constraint FK_CRIADOR foreign key(CODCRIADOR) references PARTICIPANTE(codigo),
    CONSTRAINT PK_CODIGO_EVENTO PRIMARY KEY (CODIGO)
);



CREATE TABLE EVENTO_PARTICIPANTE(
					  CODEVENTO INTEGER NOT NULL,
                      CODPARTICIPANTE INTEGER NOT NULL,
					  CODAMIGO INTEGER,
                      constraint FK_EVENTO foreign key(CODEVENTO) references EVENTO(codigo),
                      constraint fk_PARTICIPANTE foreign key(CODPARTICIPANTE) references PARTICIPANTE(codigo),
					  CONSTRAINT FK_AMIGO FOREIGN KEY (CODAMIGO) REFERENCES PARTICIPANTE(CODIGO),
                      primary key(CODEVENTO,CODPARTICIPANTE)
);

